[package]
name = "rustegex"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "2.0.3"
ahash = "0.8.12"
bit-set = "0.8.0"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "benchmark"
harness = false
